// resources/js/components/announcements/Announcement.vue
<template>
    <article class="article card" v-if="topic">
        <div class="article__container">
            <h2 class="article__heading">{{ topic.title }}</h2>
            <div class="article__date">{{ date }}</div>

            <div class="article__body" v-html="content" v-if="topic.details"></div>
            <div class="article__body" v-else>
                <div class="spinner">
                    <div class="rect1"></div>
                    <div class="rect2"></div>
                    <div class="rect3"></div>
                    <div class="rect4"></div>
                    <div class="rect5"></div>
                </div>
            </div>
            <div class="article__author" v-if="topic.details">
                Posted by&nbsp;
                <img :src="avatarUrl" width="16" :alt="`${topic.details.created_by.username}'s Avatar`"/>
                <a :href="`https://forums.projectcitybuild.com/u/${topic.details.created_by.username}`">{{ topic.details.created_by.username }}</a>
            </div>
            <div class="article__author" v-else>
                <div class="skeleton-row">
                    <div class="skeleton" style="width:200px"></div>
                    <div class="skeleton skeleton--square skeleton--dark"></div>
                    <div class="skeleton"></div>
                </div>
            </div>
        </div>
        <div class="article__footer">
            <div class="stats-container">
                <div class="stat">
                    <span class="stat__figure">{{ topic.posts_count - 1 }}</span>
                    <span class="stat__heading">Comments</span>
                </div>
                <div class="stat">
                    <span class="stat__figure">{{ topic.views }}</span>
                    <span class="stat__heading">Post Views</span>
                </div>
            </div>
            <div class="actions">
                <a class="button button--accent button--large"
                   :href="`https://forums.projectcitybuild.com/t/${topic.slug}/${topic.id}`">
                    Read Post
                    <i class="fa fa-chevron-right"></i>
                </a>
            </div>
        </div>
    </article>
</template>

<script lang="ts">
import Vue from "vue";
import * as Api from "./api";
import * as dateFns from "date-fns";

export default Vue.extend({
    name: "Announcement",

    props: {
        topic_id: Number
    },

    data() {
        return {
            topic: null as Api.DiscourseTopicDetails
        }
    },

    created() {
        Api.getTopicDetails(this.topic_id).then(topic => this.topic = topic)
    },

    computed: {
        initialPost(): Api.DiscoursePost {
            return this.topic.post_stream.posts[0]
        }

        content(): string {
            let content = this.initialPost.cooked;
            content.replace(/href="\//g, 'href="https://forums.projectcitybuild.com/');
            return content;
        },

        avatarUrl(): string {
            return "https://forums.projectcitybuild.com" + this.initialPost.avatar_template.replace('{size}', '16');
        },

        date(): string {
            return dateFns.format(this.topic.created_at, 'ddd, Do \of MMMM, YYYY');
        }
    }
});
</script>

// src/interfaces/web/assets/js/react/components/Announcement/announcement.tsx
import * as React from 'react';
import * as Api from './api';
import * as dateFns from 'date-fns';

interface InitialState {}

interface Props {
    announcement: Api.ApiTopic,
    seed: number,
}

export default class Component extends React.Component<Props, InitialState> {
    state: InitialState = {}

    createMarkup(html: string) {
        return { __html: html }
    }

    getRandom(min: number, max: number, localSeed: number = this.props.seed) : number {
        let x = Math.sin(localSeed) * 10000;
        x = x - Math.floor(x);
        x = (x * (max - min)) + min;

        return x;
    }

    renderAnnouncement(announcement: Api.ApiTopic) : React.ReactNode {
        // why do you do this to me, javascript...
        const username = (
            announcement.details && 
            announcement.details.details && 
            announcement.details.details.created_by &&
            announcement.details.details.created_by.username
        ) || "";

        const post: Api.ApiPost = 
            announcement.details &&
            announcement.details.post_stream &&
            announcement.details.post_stream.posts
                ? announcement.details.post_stream.posts[0]
                : { 
                    cooked: "", 
                    avatar_template: "",
                };

        const date = dateFns.format(announcement.created_at, 'ddd, Do \of MMMM, YYYY');
        const avatarUrl = "https://forums.projectcitybuild.com" + post.avatar_template.replace('{size}', '16')
        let markup = post.cooked;

        // convert relative urls to forum absolute urls
        markup = markup.replace(/href="\//, 'href="https://forums.projectcitybuild.com/');

        return (
            <article className="article card" key={announcement.id}>
                <div className="article__container">
                    <h2 className="article__heading">{ announcement.title }</h2>
                    <div className="article__date">{ date }</div>
                    { 
                        announcement.details
                            ? <div className="article__body" dangerouslySetInnerHTML={{ __html: markup }}></div>
                            : (
                                <div className="article__body">
                                    <div className="spinner">
                                        <div className="rect1"></div>
                                        <div className="rect2"></div>
                                        <div className="rect3"></div>
                                        <div className="rect4"></div>
                                        <div className="rect5"></div>
                                    </div>
                                </div>
                            )
                    }
                    <div className="article__author">
                        Posted by
                        <img src={avatarUrl} width="16" alt={username} />
                        <a href={`https://forums.projectcitybuild.com/u/${username}`}>{ username }</a>
                    </div>
                </div>
                <div className="article__footer">
                    <div className="stats-container">
                        <div className="stat">
                            <span className="stat__figure">{ announcement.posts_count - 1 }</span>
                            <span className="stat__heading">Comments</span>
                        </div>
                        <div className="stat">
                            <span className="stat__figure">{ announcement.views }</span>
                            <span className="stat__heading">Post Views</span>
                        </div>
                    </div>
                    <div className="actions">
                        <a className="button button--accent button--large" href={`https://forums.projectcitybuild.com/t/${announcement.slug}/${announcement.id}`}>
                            Read Post
                            <i className="fa fa-chevron-right"></i>
                        </a>
                    </div>
                </div>
            </article>
        );
    }

    renderSkeleton(index: number) : React.ReactNode {
        let bodySkeleton: Array<React.ReactNode> = [];
        for(let i = 0; i < this.getRandom(3, 6); i++) {
            bodySkeleton.push(
                <div key={i} 
                    className="skeleton" 
                    style={{width: this.getRandom(60, 100, this.props.seed + i) + '%'}}>
                </div>
            );
        }

        return (
            <article className="article card" key={index}>
                <div className="article__container">
                    <div className="article__heading">
                        <div className="skeleton skeleton--dark skeleton--large" style={{width: this.getRandom(40, 80) + '%'}}></div>
                    </div>
                    <div className="article__date">
                        <div className="skeleton" style={{width:'20%'}}></div>
                    </div>
                    <div className="article__body">{ bodySkeleton }</div>

                    <div className="article__author">
                        <div className="skeleton-row">
                            <div className="skeleton" style={{width:'200px'}}></div>
                            <div className="skeleton skeleton--square skeleton--dark"></div>
                            <div className="skeleton"></div>
                        </div>
                    </div>
                </div>
                <div className="article__footer">
                    <div className="stats-container">
                        <div className="stat">
                            <span className="stat__figure">
                                <div className="skeleton skeleton--medium skeleton--dark skeleton--middle" style={{width:'15px'}}></div>
                            </span>
                            <span className="stat__heading">
                                <div className="skeleton skeleton--small" style={{width:'50px'}}></div>
                            </span>
                        </div>
                        <div className="stat">
                            <span className="stat__figure">
                                <div className="skeleton skeleton--medium skeleton--dark skeleton--middle" style={{width:'15px'}}></div>
                            </span>
                            <span className="stat__heading">
                                <div className="skeleton skeleton--small" style={{width:'50px'}}></div>
                            </span>
                        </div>
                    </div>
                    <div className="article__actions">
                        <div className="skeleton skeleton--button"></div>
                    </div>
                </div>
            </article>
        )
    }

    render() {
        if(!this.props.announcement || !this.props.announcement.details) {
            return this.renderSkeleton(0);
        }
        return this.renderAnnouncement(this.props.announcement);
    }
}
